NAME = philo

CC = cc
CFLAGS = -Wall -Wextra -Werror
SRC = 		main.c \
			control_mutex.c \
			init.c \
			observer.c \
			time.c \
			threads.c \
			routine.c \
			utils.c \
			check.c \
			cleanup.c

OBJ = $(SRC:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
		$(CC) $(CFLAGS) $(OBJ) -o $(NAME)

clean:
	rm -rf $(OBJ)

fclean: clean
	rm -rf $(NAME)

re: fclean all

.PHONY: all clean fclean re



